# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questionboard.Question'),
            preserve_default=False,
        ),
    ]
