# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionboard', '0002_auto_20160518_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
